QquickQqueue/QquickQqueue-BackEnd

- build.gradle
- src/main/java/com/example/qquickqqueue/redis/config/RedisConfig.java
- src/main/java/com/example/qquickqqueue/redis/util/RedisUtil.java
- src/main/java/com/example/qquickqqueue/security/config/WebSecurityConfig.java
- src/main/java/com/example/qquickqqueue/security/jwt/JwtAuthFilter.java
- src/main/java/com/example/qquickqqueue/security/jwt/JwtUtil.java
- src/main/java/com/example/qquickqqueue/security/jwt/TokenDto.java
- src/main/java/com/example/qquickqqueue/security/userDetails/UserDetailsImpl.java
- src/main/java/com/example/qquickqqueue/security/userDetails/UserDetailsServiceImpl.java
- src/main/java/com/example/qquickqqueue/util/Timestamped.java
> feat : security 및 redis 기능 구현 

- src/main/java/com/example/qquickqqueue/domain/members/entity/Members.java
- src/main/java/com/example/qquickqqueue/domain/members/repository/MembersRepository.java
히힛 ;) 
entity 애너테이션이랑 findbyemail 입니다요  ~ :-)
> feat : members entity 애너테이션 및 repository 내용 추가 

- build.gradle
- src/main/java/com/example/qquickqqueue/domain/musical/controller/MusicalController.java
- src/main/java/com/example/qquickqqueue/domain/musical/dto/MusicalResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/musical/service/MusicalService.java
- src/test/java/com/example/qquickqqueue/domain/musical/controller/MusicalControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/musical/service/MusicalServiceTest.java
test : 뮤지컬 상세 조회 API test code 작성
chore : jacoco 플러그인 추가
> feat : 뮤지컬 상세 조회 API 구현 (stadium 연관관계 맺기 전)

- src/main/java/com/example/qquickqqueue/domain/actor/entity/Actor.java
- src/main/java/com/example/qquickqqueue/domain/casting/entity/Casting.java
- src/main/java/com/example/qquickqqueue/domain/members/entity/Members.java
- src/main/java/com/example/qquickqqueue/domain/musical/entity/Musical.java
- src/main/java/com/example/qquickqqueue/domain/schedule/entity/Schedule.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/entity/ScheduleSeat.java
- src/main/java/com/example/qquickqqueue/domain/seat/entity/Seat.java
- src/main/java/com/example/qquickqqueue/domain/seatGrade/entity/SeatGrade.java
- src/main/java/com/example/qquickqqueue/domain/stadium/entity/Stadium.java
- src/main/java/com/example/qquickqqueue/domain/ticket/entity/Ticket.java
musical - casting (양방향) 제외 ManyToOne 단방향
> feat : 연관관계 설정

- src/main/java/com/example/qquickqqueue/domain/casting/entity/Casting.java
- src/main/java/com/example/qquickqqueue/domain/casting/repository/CastingRepository.java
- src/main/java/com/example/qquickqqueue/domain/musical/controller/MusicalController.java
- src/main/java/com/example/qquickqqueue/domain/musical/dto/MusicalResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/musical/dto/MusicalRoundInfoResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/musical/service/MusicalService.java
- src/main/java/com/example/qquickqqueue/domain/schedule/dto/ScheduleResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/schedule/entity/Schedule.java
- src/main/java/com/example/qquickqqueue/domain/schedule/repository/ScheduleRepository.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/entity/ScheduleSeat.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/repository/ScheduleSeatRepository.java
- src/main/java/com/example/qquickqqueue/domain/seat/entity/Seat.java
- src/main/java/com/example/qquickqqueue/domain/seatGrade/entity/SeatGrade.java
- src/test/java/com/example/qquickqqueue/domain/musical/controller/MusicalControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/musical/service/MusicalServiceTest.java
test : 해당 method test code 작성 <br>
refactor : 뮤지컬 상세 조회 API 반환값에 스케줄 좌석 추가 <br>
feat : 연관관계 추가
> feat : 뮤지컬 회차별 남은 좌석, 배우 조회 API 구현

- src/main/java/com/example/qquickqqueue/domain/members/controller/MembersController.java
- src/main/java/com/example/qquickqqueue/domain/members/dto/request/LoginRequestDto.java
- src/main/java/com/example/qquickqqueue/domain/members/dto/request/SignupRequestDto.java
- src/main/java/com/example/qquickqqueue/domain/members/entity/Members.java
- src/main/java/com/example/qquickqqueue/domain/members/service/MembersService.java
- src/main/java/com/example/qquickqqueue/security/jwt/JwtUtil.java
- src/test/java/com/example/qquickqqueue/domain/members/controller/MembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/service/MembersServiceTest.java
확.. 확인 해주실래요~? ;) 
여러분 덕분에 해낼 수 있었습니다.
> feat : 회원가입, 로그인, 로그아웃 기능 및 테스트 코드 추가 

- src/main/java/com/example/qquickqqueue/domain/members/controller/MembersController.java
- src/main/java/com/example/qquickqqueue/domain/members/dto/request/WithdrawalDto.java
- src/main/java/com/example/qquickqqueue/domain/members/entity/Members.java
- src/main/java/com/example/qquickqqueue/domain/members/service/MembersService.java
- src/test/java/com/example/qquickqqueue/domain/members/controller/MembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/service/MembersServiceTest.java
import 다음부터 꼭 지울게요.. 
한 번만 봐주세요..
> feat : 회원 탈퇴 기능 및 테스트 코드 추가

- src/main/java/com/example/qquickqqueue/domain/members/controller/MembersController.java
- src/main/java/com/example/qquickqqueue/domain/members/dto/response/MemberInfoResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/members/service/MembersService.java
- src/main/java/com/example/qquickqqueue/domain/ticket/service/TicketService.java
- src/test/java/com/example/qquickqqueue/domain/members/controller/MembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/service/MembersServiceTest.java
feat : 회원정보 조회
test : 회원정보 조회 테스트 코드
> feat : 회원정보 조회

- src/main/java/com/example/qquickqqueue/domain/members/controller/KakaoMembersController.java
- src/main/java/com/example/qquickqqueue/domain/members/dto/response/MemberInfoResponseDto.java
- src/main/java/com/example/qquickqqueue/domain/members/entity/Members.java
- src/main/java/com/example/qquickqqueue/domain/members/service/KakaoMembersService.java
- src/main/java/com/example/qquickqqueue/domain/members/service/MembersService.java
- src/main/java/com/example/qquickqqueue/security/config/WebSecurityConfig.java
- src/main/java/com/example/qquickqqueue/security/jwt/JwtUtil.java
- src/test/java/com/example/qquickqqueue/domain/members/controller/KakaoMembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/controller/MembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/service/MembersServiceTest.java
> feat : 소셜로그인 로직 추가 

- src/main/java/com/example/qquickqqueue/domain/musical/controller/MusicalController.java
- src/main/java/com/example/qquickqqueue/security/config/WebSecurityConfig.java
fix : pageable size 10 -> 8 변경
feat : 검색 api securityConfig 허용
> refactor : pageable size 10 -> 8 변경 & feat : 검색 api securityConfig 허용

- src/main/java/com/example/qquickqqueue/domain/stadium/controller/StadiumController.java
- src/main/java/com/example/qquickqqueue/domain/stadium/dto/request/StadiumRequestDto.java
- src/main/java/com/example/qquickqqueue/domain/stadium/service/StadiumService.java
- src/test/java/com/example/qquickqqueue/domain/musical/controller/MusicalControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/musical/service/MusicalServiceTest.java
- src/test/java/com/example/qquickqqueue/domain/stadium/controller/StadiumControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/stadium/service/StadiumServiceTest.java
> feat : 공연장 등록 API 구현 및 Test Code 작성

- src/main/java/com/example/qquickqqueue/security/config/WebSecurityConfig.java
feat : securityConfig - setExposedHeaders 추가
> feat : securityConfig - setExposedHeaders 추가

- src/main/java/com/example/qquickqqueue/domain/members/controller/MembersController.java
> refactor : 로그아웃 api / 추가

- src/main/java/com/example/qquickqqueue/domain/members/service/KakaoMembersService.java
- src/main/java/com/example/qquickqqueue/domain/members/service/MembersService.java
- src/main/java/com/example/qquickqqueue/domain/musical/service/MusicalService.java
- src/main/java/com/example/qquickqqueue/domain/ticket/service/TicketService.java
- src/main/java/com/example/qquickqqueue/exception/GlobalExceptionHandler.java
- src/main/java/com/example/qquickqqueue/security/jwt/JwtUtil.java
> feat : 예외처리 추가 및 예외 변경

- src/test/java/com/example/qquickqqueue/QquickQqueueApplicationTests.java
- src/test/java/com/example/qquickqqueue/security/jwt/JwtUtilTest.java
> test : JwtUtil 테스트 코드 

- src/test/java/com/example/qquickqqueue/domain/members/controller/KakaoMembersControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/members/entity/membersTest.java
test : kakaoWithdrawalTest 작성
test : setIsKakaoEmailTest 작성
> test : kakaoWithdrawalTest , setIsKakaoEmailTest 작성

- src/main/java/com/example/qquickqqueue/domain/musical/entity/Musical.java
- src/main/java/com/example/qquickqqueue/security/config/WebSecurityConfig.java
refactor : permitAll 수정, Member Entity casting oneToMany 삭제
> refactor : permitAll 수정, Member Entity casting oneToMany 삭제

- build.gradle
- src/main/java/com/example/qquickqqueue/domain/musical/controller/MusicalController.java
- src/main/java/com/example/qquickqqueue/domain/musical/service/MusicalService.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/repository/ScheduleSeatCustomRepository.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/repository/ScheduleSeatRepository.java
- src/main/java/com/example/qquickqqueue/domain/scheduleSeat/repository/impl/ScheduleSeatCustomRepositoryImpl.java
- src/main/java/com/example/qquickqqueue/domain/ticket/controller/TicketController.java
- src/main/java/com/example/qquickqqueue/util/QueryDslConfig.java
- src/test/java/com/example/qquickqqueue/security/jwt/JwtUtilTest.java
> refactor : 뮤지컬 좌석 조회 리펙토링

- src/main/java/com/example/qquickqqueue/domain/musical/service/MusicalService.java
- src/test/java/com/example/qquickqqueue/domain/musical/controller/MusicalControllerTest.java
- src/test/java/com/example/qquickqqueue/domain/musical/repository/MusicalJdbcRepositoryTest.java
- src/test/java/com/example/qquickqqueue/domain/musical/service/MusicalServiceTest.java
musicalService 수정에 따른 test 추가 및 변경
> test : musical service 수정에 따른 test 추가 및 변경 

- src/test/java/com/example/qquickqqueue/domain/scheduleSeat/repository/impl/ScheduleSeatCustomRepositoryImplTest.java
- src/test/java/com/example/qquickqqueue/domain/scheduleSeat/service/ScheduleSeatServiceTest.java
test : ScheduleSeatService, ScheduleSeatCustomRepositoryImpl Test 작성
> test : ScheduleSeatService, ScheduleSeatCustomRepositoryImpl Test 작성
